#!/usr/bin/env groovy

//ENV Vars
def TOOLS_NAMESPACE = "s4g19x-pwei1018-openshift201-may2019-tools"
def DEV_NAMESPACE = "s4g19x-pwei1018-openshift201-may2019-dev"
def PROD_NAMESPACE = "s4g19x-pwei1018-openshift201-may2019-prod"


//Pipeline
node {
    stage ('Build Stage'){
        dir ('simple_pipeline') {
            checkout scm
            sh "oc get projects"
        }
    }
}