apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: python
labels:
  app: ${NAME}${SUFFIX}
  phase: build
parameters:
  - name: NAME
    value: patroni
  - name: SUFFIX
  - name: VERSION
    description: Ouput version
    value: "v10-latest"
  - name: GIT_URI
    value: https://github.com/BCDevOps/platform-services.git
  - name: GIT_REF
    value: master
  - name: PYTHON_VERSION
    value: "3.7.3"
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations: {}
    creationTimestamp: null
    generation: 1
    name: python
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: registry.hub.docker.com/library/python:3.7.3
      generation: 1
      importPolicy: {}
      name: "python-3.7.3"
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""