apiVersion: v1
data:
  GF_DATABASE_TYPE: postgres
  GF_DATABASE_HOST: ${PATRONI_SERVICE}
  GF_DATABASE_NAME:
    valueFrom:
    secretKeyRef:
        key: app-db-name
        name: ${PATRONI_SECRET}
 GF_DATABASE_USER:
    valueFrom:
    secretKeyRef:
        key: app-db-username
        name: ${PATRONI_SECRET}
 GF_DATABASE_PASSWORD:
    valueFrom:
    secretKeyRef:
        key: app-db-password
        name: ${PATRONI_SECRET}
kind: ConfigMap
metadata:
labels:
    app: ${GRAFANA_SERVICE_NAME}
name: ${GRAFANA_SERVICE_NAME}-datasources
parameters:
- description: The name of the OpenShift Service exposed for the database.
  displayName: Grafana Service Name
  name: GRAFANA_SERVICE_NAME
  required: true
  value: grafana